== My Alacritty config

The theme repo

 https://github.com/alacritty/alacritty-theme


=== My zshrc part
 This is only for the fzf and fd, eza, and a few other tools I installed with Alacritty. 

.zshrc
 
    source ~/.oh-my-zsh/fzf-git.sh
    eval "$(fzf --zsh)"
    export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"
    export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"
    _fzf_comprun() {
       local command=$1
       shift
       case "$command" in
          cd)           fzf --preview 'eza --tree --color=always {} |head -200' "$@" ;;
          export|unset) fzf --preview "eval 'echo \$' {}" "$@" ;;
          ssh)          fzf --preview 'dig {}'  "$@" ;;
           *)           fzf --preview "--preview 'bat -n --color=always --line-range :500 {}'" "$@" ;;
        esac
    }
    export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"
    #export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' --color=fg:#d0d0d0,fg+:#d0d0d0,bg:#121212,bg+:#262626 --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87,marker:#87ff00 --color=prompt:#d7005f,spinner:#af5f
          │ ff,pointer:#af5fff,header:#87afaf --color=border:#262626,label:#aeaeae,query:#d9d9d9 --border="double" --border-label="" --preview-window="border-sharp" --padding="" --margin="" --prompt="> " -
    -marker=">" --pointer="◆" --separator="─" --scrollbar="│" --layout="reverse-list"'
    #export FZF_DEFAULT_OPTS="--height=40% --layout=reverse --info=inline --border --margin=1 --padding=1"
     # Use fd (https://github.com/sharkdp/fd) for listing path candidates.
     # - The first argument to the function ($1) is the base path to start traversal
     # - See the source code (completion.(bash,zsh}) for the details.
     _fzf_compgen_path () {
        fd --hidden --exclude •git . "$1"
     }
     _fzf_compgen_dir() {
        fd --type=d --hidden --exclude •git . "$1"
     }
     alias ls="eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions"
     alias ll="eza --color=always --long --git --no-filesize --icons=always"
    HISTFILE=$HOME/.zhistory
    SAVEHIST=3000
    HISTSIZE=999
    setopt share_history
    setopt hist_expire_dups_first
    setopt hist_ignore_dups
    setopt hist_verify
    # completion using arrow keys (based on history)
    bindkey '^[[A' history-search-backward
    bindkey '^[[B' history-search-forward
    eval "$(zoxide init zsh)"
    alias cd="z"
    eval "$(atuin init zsh)"

